apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: example
spec:
  refreshInterval: 12h
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: secret-to-be-created
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: formadoresit 

