apiVersion: v1
kind: Secret
metadata:
  name: awssm-secret
data:
  access-key: ACCESS-KEY
  secret-access-key: SECRET-KEY

---

apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: aws-secretsmanager
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-central-1
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: awssm-secret
            key: access-key
          secretAccessKeySecretRef:
            name: awssm-secret
            key: secret-access-key